import type { INodeProperties } from 'n8n-workflow';

export const eventsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['events'] } },
		options: [
<<<<<<< HEAD
			{ name: 'Attendance', value: 'attendance', description: 'POST /v1/events/{event_id}/attendance', action: 'Events: Attendance',},
			{ name: 'Create', value: 'create', description: 'POST /v1/events', action: 'Events: Create an event',},
			{ name: 'Get By ID', value: 'getById', description: 'GET /v1/events/{ID}', action: 'Events: Get Details by ID',},
			{ name: 'Get Many', value: 'getMany', description: 'GET /v1/events', action: 'Events: Get Many',},
			{ name: 'Get Types', value: 'getTypes', description: 'GET /v1/events/types', action: 'Events: Get Event Types',},
			{ name: 'RSVP', value: 'rsvp', description: 'PUT /v1/events/{id}/rsvp', action: 'Events: RSVP',},
=======
			{ name: 'Get Many', value: 'getMany', description: 'GET /v1/events', action: 'Events: Get Many',},
			{ name: 'Get By ID', value: 'getById', description: 'GET /v1/events/{ID}', action: 'Events: Get Details by ID',},
			{ name: 'Create', value: 'create', description: 'POST /v1/events', action: 'Events: Create an event',},
			{ name: 'Get Types', value: 'getTypes', description: 'GET /v1/events/types', action: 'Events: Get Event Types',},
>>>>>>> 44105df (2026-04-08)
		],
		default: 'getMany',
	},
];

export const eventsFields: INodeProperties[] = [
	{
		displayName: 'Start On',
		name: 'startOn',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['events'], operation: ['getMany'] } },
		default: '',
		placeholder: '2026-01-01',
		description: 'ISO date (YYYY-MM-DD)',
	},
	{
		displayName: 'End On',
		name: 'endOn',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['events'], operation: ['getMany'] } },
		default: '',
		placeholder: '2026-01-31',
		description: 'ISO date (YYYY-MM-DD)',
	},
	{
		displayName: 'Event ID',
		name: 'eventId',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['events'], operation: ['getById', 'rsvp', 'attendance'] } },
		default: 0,
	},
	{
		displayName: 'Create Body',
		name: 'createBody',
		type: 'json',
		required: true,
		displayOptions: { show: { resource: ['events'], operation: ['create'] } },
		default: '{}',
		description: 'JSON body matching postV1Events in TroopTrack Swagger',
	},
	{
		displayName: 'RSVP Yes User IDs',
		name: 'rsvpYesUserIds',
		type: 'json',
		displayOptions: { show: { resource: ['events'], operation: ['rsvp'] } },
		default: '[]',
		description: 'JSON array of user IDs to mark as yes (coming), e.g. [101, 102]',
	},
	{
		displayName: 'RSVP No User IDs',
		name: 'rsvpNoUserIds',
		type: 'json',
		displayOptions: { show: { resource: ['events'], operation: ['rsvp'] } },
		default: '[]',
		description: 'JSON array of user IDs to mark as no (not coming), e.g. [201, 202]',
	},
	{
		displayName: 'RSVP TBD User IDs',
		name: 'rsvpTbdUserIds',
		type: 'json',
		displayOptions: { show: { resource: ['events'], operation: ['rsvp'] } },
		default: '[]',
		description: 'JSON array of user IDs to mark as tbd (no clue), e.g. [301, 302]',
	},
	{
		displayName: 'Attendance Attended User IDs',
		name: 'attendanceAttendedUserIds',
		type: 'json',
		displayOptions: { show: { resource: ['events'], operation: ['attendance'] } },
		default: '[]',
		description: 'JSON array of user IDs to mark as attended (1), e.g. [101, 102]',
	},
	{
		displayName: 'Attendance Did Not Attend User IDs',
		name: 'attendanceDidNotAttendUserIds',
		type: 'json',
		displayOptions: { show: { resource: ['events'], operation: ['attendance'] } },
		default: '[]',
		description: 'JSON array of user IDs to mark as did not attend (0), e.g. [201, 202]',
	},
	{
		displayName: 'Attendance No Clue User IDs',
		name: 'attendanceNoClueUserIds',
		type: 'json',
		displayOptions: { show: { resource: ['events'], operation: ['attendance'] } },
		default: '[]',
		description: 'JSON array of user IDs to mark as no clue (2), e.g. [301, 302]',
	},
];
